// fixtures/manifest.json: provenance without personal data, the files, and what the fixture
// tests expect (which feed edges rules v1 removes).

import { readFileSync } from "node:fs";
import { createAdRule, type AdRules } from "../../src/lib/adRules";
import { NdjsonStreamFilter } from "../../src/lib/ndjsonFilter";
import { RULES } from "../../src/lib/redact";
import type { Obj, Session } from "../findings/session";
import { SANITIZER_VERSION, type FixtureSet } from "./sanitize";

/** Edge indices rules v1 removes from a feed fixture, and how many documents it drops. */
export function expectedAds(text: string, rules: AdRules): { removed: number[]; droppedDocuments: number; finalMarkers: number } {
  const rule = createAdRule(rules);
  const f = new NdjsonStreamFilter(rule);
  f.push(new TextEncoder().encode(text));
  f.end();
  return { removed: rule.report.removed.map((r) => r.index), droppedDocuments: rule.report.droppedDocuments, finalMarkers: rule.report.finalMarkers };
}

function constantField(s: Session, name: string): string | null {
  for (const r of s.graphql()) {
    const v = s.field(r, name);
    if (typeof v === "string") return v;
  }
  return null;
}

export function buildFixtureManifest(sessions: Session[], set: FixtureSet, rulesFile: string): Obj {
  const rules = JSON.parse(readFileSync(rulesFile, "utf8")) as AdRules;
  const expected: Obj = {};
  for (const e of set.entries) {
    if (e.query !== "CometNewsFeedPaginationQuery" && e.query !== "CometModernHomeFeedQuery") continue;
    if (e.kind === "graphql-request") continue;
    expected[e.file] = expectedAds(set.files.get(e.file)!, rules);
  }
  return {
    about: "Sanitized, structure-only fixtures of the site's logged-in GraphQL traffic (fixtures/README.md). Generated by tools/capture-tools.sh fixtures; do not edit by hand.",
    sanitizerVersion: SANITIZER_VERSION,
    redactionRulesVersion: (RULES as unknown as { version?: number }).version ?? null,
    adRules: { file: "rules/ads-v1.json", version: rules.version },
    sources: sessions.map((s) => ({
      session: s.sourceId,
      date: new Date(Number(s.session["startedAt"] ?? 0)).toISOString().slice(0, 10),
      site: constantField(s, "__crn") === null ? "unknown" : "www.facebook.com (desktop user agent)",
      siteRevision: constantField(s, "__spin_r"),
      clientRevision: constantField(s, "__rev"),
      geckoview: s.session["geckoview"] ?? null,
      extension: (s.session["extension"] as Obj | undefined)?.["version"] ?? null,
      app: (s.session["app"] as Obj | undefined)?.["version"] ?? null,
    })),
    stats: {
      files: set.files.size,
      bytes: set.entries.reduce((a, e) => a + e.bytes, 0),
      strings: set.stats.strings,
      stringsKept: set.stats.kept,
      stringsReplaced: set.stats.replaced,
      urlsReplaced: set.stats.urls,
      numbersRemapped: set.stats.numbersRemapped,
      keysReplaced: set.stats.keysReplaced,
    },
    files: set.entries,
    expected: { adRemovals: expected },
  };
}
